### ISSUE TITLE
AttributeError: module 'tickterial.tickloader' has no attribute 'download in "Module usage" example

### ISSUE THREAD

**Issue by Redro38** [drui9/tickterial#2]
Hi !

When i tried to use your "Module usage" example, I have an error :
`AttributeError: module 'tickterial.tickloader' has no attribute 'download'`

When i use tickloader.Tickloader.download instead of tickloader.download:
```
period = datetime.now() - timedelta(minutes=60) # previous hour
tickloader.Tickloader.download(symbol='GBPUSD', hour=period)
```

I found the function download but I need to give a self arguments :
`Tickloader.download() missing 1 required positional argument: 'self'`

Can anybody help me ?

**Comment by drui9** [comment]
Try this format:
`from datetime import datetime
from tickterial import Tickloader


def test_download():
	tickloader = Tickloader()
	period = datetime(hour=17, day=8,month=4, year=2024)
	data = tickloader.download('GBPUSD', period)
	#
	ticks = list()
	for tick in data:
		ticks.append(tick)
	if ticks:
		print(f'{period} tick count: {len(ticks)}')
		print(ticks[0])
	else:
		print('No data!')

test_download()
print('--end--')`

**Comment by drui9** [comment]
You need:
```python
tickloader = Tickloader() # tickloader.download is an instance method. You need to instantiate Tickloader first.
```

**Comment by drui9** [comment]
API Misuse.
Additional documentation will be a plus.

**Comment by Redro38** [comment]
Thanks for your reply. It works now.

**Comment by drui9** [comment]
Have fun using it. I disliked keeping it to myself. :)
