### ISSUE TITLE
Importing tick data into meta trader 4

### ISSUE THREAD

**Issue by Jacek-ghub** [drui9/tickterial#4]
What would be the best way of importing that tick data into mt4 for backtesting purposes?

Would appreciate any guidance on it.

**Comment by drui9** [comment]
You need to convert the downloaded .csv tick data into .fxt and .hst history data used by MetaTrader 4, which has an import option.
![Screenshot_20241028-134533](https://github.com/user-attachments/assets/f3b8a68f-6bbd-4a23-a723-9b4ebdc101e0)

**Comment by Jacek-ghub** [comment]
Thank you.

Finally, I got the hst file imported.  However, I am still stuck with the fxt file.  History Center doesn't have an option to import that file (I tried to force it, but it didn't work).
